title: AmidamaruQ Writeups
description: Райтапы от Хоуми
remote_theme: mmistakes/minimal-mistakes@4.24.0
theme_mode: dark
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
